name: CI/CD - Build & Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Eureka
        uses: docker/build-push-action@v6
        with:
          context: ./eureka-server
          push: true
          tags: |
            yourdockerhub/eureka-server:latest
            yourdockerhub/eureka-server:${{ github.sha }}

      - name: Build & Push API Gateway
        uses: docker/build-push-action@v6
        with:
          context: ./api-gateway
          push: true
          tags: |
            yourdockerhub/api-gateway:latest
            yourdockerhub/api-gateway:${{ github.sha }}

      - name: Build & Push Book Service
        uses: docker/build-push-action@v6
        with:
          context: ./book-service
          push: true
          tags: |
            yourdockerhub/book-service:latest
            yourdockerhub/book-service:${{ github.sha }}

      - name: Build & Push Review Service
        uses: docker/build-push-action@v6
        with:
          context: ./review-service
          push: true
          tags: |
            yourdockerhub/review-service:latest
            yourdockerhub/review-service:${{ github.sha }}
