version: "3.8"

services:
  eureka-server:
    image: mtodorov08/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    image: mtodorov08/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  book-service:
    image: mtodorov08/book-service:latest
    container_name: book-service
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  review-service:
    image: mtodorov08/review-service:latest
    container_name: review-service
    ports:
      - "8082:8082"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
