apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: mtodorov08/book-service:latest
          env:
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: SPRING_RABBITMQ_HOST
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: EUREKA_URL
            - name: SPRING_SECURITY_USER_NAME
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: SECURITY_USER
            - name: SPRING_SECURITY_USER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: SECURITY_PASSWORD
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "book-service"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: microservices
spec:
  selector:
    app: book-service
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
