name: CI/CD - Build & Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
        # --------------------------
        # 1. Install JDK 17 for Maven
        # --------------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # --------------------------
      # 2. Build all services with Maven
      # --------------------------
      - name: Build Eureka Server
        run: mvn -q -DskipTests package --file microservices/eureka-server/pom.xml

      - name: Build Book Service
        run: mvn -q -DskipTests clean install --file microservices/book-service/pom.xml

      - name: Build API Gateway
        run: mvn -q -DskipTests package --file microservices/api-gateway/pom.xml

      - name: Build Review Service
        run: mvn -q -DskipTests package --file microservices/review-service/pom.xml


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Eureka
        uses: docker/build-push-action@v6
        with:
          context: ./microservices/eureka-server
          push: true
          tags: |
            mtodorov08/eureka-server:latest
            mtodorov08/eureka-server:${{ github.sha }}

      - name: Build & Push API Gateway
        uses: docker/build-push-action@v6
        with:
          context: ./microservices/api-gateway
          push: true
          tags: |
            mtodorov08/api-gateway:latest
            mtodorov08/api-gateway:${{ github.sha }}

      - name: Build & Push Book Service
        uses: docker/build-push-action@v6
        with:
          context: ./microservices/book-service
          push: true
          tags: |
            mtodorov08/book-service:latest
            mtodorov08/book-service:${{ github.sha }}

      - name: Build & Push Review Service
        uses: docker/build-push-action@v6
        with:
          context: ./microservices/review-service
          push: true
          tags: |
            mtodorov08/review-service:latest
            mtodorov08/review-service:${{ github.sha }}

      - name: Test API Gateway Endpoint
        with:
          context: ./microservices
          run: |
             docker compose up -d
             sleep 10
             curl -s -X POST -H "Content-Type: application/json" -d '{"title":"1984","author":"Orwell"}' http://localhost:8080/book-service/api/books
             curl http://localhost:8080/book-service/api/books
             curl http://localhost:8080/review-service/api/reviews/book/1
             curl http://localhost:8080/book-service/books/view
